import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const creditCards = [
  // HDFC Bank Cards
  {
    name: 'HDFC Regalia',
    bank: 'HDFC Bank',
    category: 'rewards',
    annualFee: 2500,
    joiningFee: 2500,
    rewardPoints: '4 reward points per ₹150 spent. 1 reward point = ₹0.50',
    welcomeBenefits: '2500 reward points on payment of joining/renewal fee',
    loungeAccess: 'Domestic: 12 complimentary visits per year. International: 6 complimentary visits per year',
    fuelBenefits: '1% fuel surcharge waiver on transactions between ₹400 to ₹5000',
    offers: 'Dining delights - up to 15% discount at partner restaurants',
    otherBenefits: 'Air accident cover of ₹1 crore, Golf privilege program, Priority customer service',
    eligibility: 'Net monthly income ₹50,000+',
  },
  {
    name: 'HDFC Infinia',
    bank: 'HDFC Bank',
    category: 'travel',
    annualFee: 12500,
    joiningFee: 12500,
    rewardPoints: '5 reward points per ₹150 spent. Accelerated points on travel and hotels',
    welcomeBenefits: '12500 reward points on payment of joining fee',
    loungeAccess: 'Unlimited domestic and international lounge access with Priority Pass',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'Complimentary golf games, spa services, luxury hotel stays',
    otherBenefits: 'Concierge services, exclusive access to Infinia experiences, air accident cover of ₹3 crore',
    eligibility: 'Net monthly income ₹2,00,000+ or invitation only',
  },
  {
    name: 'HDFC MoneyBack+',
    bank: 'HDFC Bank',
    category: 'cashback',
    annualFee: 500,
    joiningFee: 500,
    rewardPoints: '2% cashback on online spends. 20% cashback on Swiggy, Zomato, Ola, Uber',
    welcomeBenefits: '₹500 Amazon voucher on spends of ₹10,000 in first 90 days',
    loungeAccess: '8 complimentary domestic lounge visits per year',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'Special cashback on online shopping platforms',
    otherBenefits: 'Zero lost card liability, air accident cover of ₹10 lakh',
    eligibility: 'Net monthly income ₹25,000+',
  },

  // SBI Cards
  {
    name: 'SBI Card Elite',
    bank: 'SBI Card',
    category: 'rewards',
    annualFee: 4999,
    joiningFee: 4999,
    rewardPoints: '5 reward points per ₹100 spent on dining, departmental stores, grocery',
    welcomeBenefits: 'Complimentary Club Vistara membership',
    loungeAccess: '8 domestic and 4 international lounge visits per year',
    fuelBenefits: '1% fuel surcharge waiver across all fuel stations',
    offers: 'Up to 15% off on dining, movies, and shopping',
    otherBenefits: 'Golf lessons, movie vouchers, complimentary club membership',
    eligibility: 'Net annual income ₹7,50,000+',
  },
  {
    name: 'SBI SimplyCLICK',
    bank: 'SBI Card',
    category: 'shopping',
    annualFee: 499,
    joiningFee: 499,
    rewardPoints: '10 reward points per ₹100 on Amazon, BookMyShow, Cleartrip, Lenskart, Netmeds',
    welcomeBenefits: '₹500 Amazon gift voucher on payment of joining fee',
    loungeAccess: 'Not available',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'Exclusive offers on partner platforms - Amazon, Flipkart, etc.',
    otherBenefits: 'Zero liability on lost card, contactless payment',
    eligibility: 'Net monthly income ₹20,000+',
  },
  {
    name: 'SBI Card PRIME',
    bank: 'SBI Card',
    category: 'fuel',
    annualFee: 2999,
    joiningFee: 2999,
    rewardPoints: '10 reward points per ₹100 spent on dining, movies, grocery',
    welcomeBenefits: '4000 bonus reward points on annual fee payment',
    loungeAccess: '8 complimentary domestic and 4 international lounge visits',
    fuelBenefits: '1% fuel surcharge waiver across all petrol pumps',
    offers: 'Milestone benefits - movie vouchers, shopping vouchers',
    otherBenefits: 'Wellness benefits, monthly movie vouchers',
    eligibility: 'Net monthly income ₹25,000+',
  },

  // ICICI Bank Cards
  {
    name: 'ICICI Bank Sapphiro',
    bank: 'ICICI Bank',
    category: 'travel',
    annualFee: 3500,
    joiningFee: 3500,
    rewardPoints: '4 reward points per ₹100 spent on travel, dining, international spends',
    welcomeBenefits: 'Welcome vouchers worth ₹4000',
    loungeAccess: '8 domestic and 4 international lounge visits per quarter',
    fuelBenefits: '2.5% value back on fuel spends at any petrol pump',
    offers: 'Buy 1 Get 1 on movie tickets at BookMyShow',
    otherBenefits: 'Golf privileges, travel insurance, concierge services',
    eligibility: 'Net monthly income ₹50,000+',
  },
  {
    name: 'ICICI Bank Amazon Pay',
    bank: 'ICICI Bank',
    category: 'cashback',
    annualFee: 0,
    joiningFee: 0,
    rewardPoints: '5% cashback on Amazon purchases for Prime members. 3% for others',
    welcomeBenefits: '₹500 Amazon gift card on card activation',
    loungeAccess: 'Not available',
    fuelBenefits: 'No fuel benefits',
    offers: '2% cashback on food delivery and travel bookings via Amazon',
    otherBenefits: '1% cashback on other purchases',
    eligibility: 'Net monthly income ₹20,000+',
  },
  {
    name: 'ICICI Bank Coral',
    bank: 'ICICI Bank',
    category: 'rewards',
    annualFee: 500,
    joiningFee: 500,
    rewardPoints: '2 reward points per ₹100 spent',
    welcomeBenefits: 'Welcome vouchers worth ₹500',
    loungeAccess: '4 complimentary domestic lounge visits per year',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'Discount on dining and shopping',
    otherBenefits: 'Zero lost card liability, interest-free credit period',
    eligibility: 'Net monthly income ₹30,000+',
  },

  // Axis Bank Cards
  {
    name: 'Axis Bank Magnus',
    bank: 'Axis Bank',
    category: 'travel',
    annualFee: 12500,
    joiningFee: 12500,
    rewardPoints: '12 EDGE Miles per ₹200 on travel, hotels. 1 Mile = ₹1',
    welcomeBenefits: 'Welcome gift vouchers',
    loungeAccess: 'Unlimited domestic and international lounge access',
    fuelBenefits: 'Fuel surcharge waiver',
    offers: 'Complimentary Taj InnerCircle membership, golf games',
    otherBenefits: 'Travel insurance, concierge services, milestone benefits',
    eligibility: 'Net monthly income ₹2,50,000+ or invitation only',
  },
  {
    name: 'Axis Bank Flipkart',
    bank: 'Axis Bank',
    category: 'shopping',
    annualFee: 500,
    joiningFee: 500,
    rewardPoints: '4% cashback on Flipkart and partner platforms. 1.5% on others',
    welcomeBenefits: '₹500 Flipkart gift voucher on card activation',
    loungeAccess: 'Not available',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'Exclusive offers during Flipkart Big Billion Days',
    otherBenefits: 'Contactless payment, zero liability on lost card',
    eligibility: 'Net monthly income ₹15,000+',
  },
  {
    name: 'Axis Bank Vistara',
    bank: 'Axis Bank',
    category: 'travel',
    annualFee: 1500,
    joiningFee: 1500,
    rewardPoints: '4 CV Points per ₹200 on regular spends. Bonus on Vistara bookings',
    welcomeBenefits: 'Club Vistara Silver membership',
    loungeAccess: 'Domestic lounge access as per membership tier',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'Milestone benefits - complimentary flight tickets',
    otherBenefits: 'Travel insurance, priority check-in',
    eligibility: 'Net monthly income ₹25,000+',
  },

  // Kotak Mahindra Bank Cards
  {
    name: 'Kotak 811 Credit Card',
    bank: 'Kotak Mahindra Bank',
    category: 'entry-level',
    annualFee: 0,
    joiningFee: 0,
    rewardPoints: '4 reward points per ₹150 spent',
    welcomeBenefits: 'Digital first credit card with instant approval',
    loungeAccess: 'Not available',
    fuelBenefits: 'No fuel benefits',
    offers: 'Merchant offers on partner platforms',
    otherBenefits: 'Zero annual fee, contactless payment',
    eligibility: 'Net monthly income ₹15,000+',
  },
  {
    name: 'Kotak Royale Signature',
    bank: 'Kotak Mahindra Bank',
    category: 'rewards',
    annualFee: 999,
    joiningFee: 999,
    rewardPoints: '4 reward points per ₹150 on departmental stores, dining. 2 on others',
    welcomeBenefits: '2500 welcome reward points',
    loungeAccess: '8 complimentary domestic lounge visits per year',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'Movie and dining discounts',
    otherBenefits: 'Travel insurance, zero lost card liability',
    eligibility: 'Net monthly income ₹35,000+',
  },

  // IndusInd Bank Cards
  {
    name: 'IndusInd Bank Pinnacle',
    bank: 'IndusInd Bank',
    category: 'rewards',
    annualFee: 5000,
    joiningFee: 5000,
    rewardPoints: '3 reward points per ₹150 spent. Bonus on travel and dining',
    welcomeBenefits: 'Welcome bonus of 10,000 reward points',
    loungeAccess: 'Unlimited domestic and 6 international lounge visits per quarter',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'Golf privileges, movie benefits',
    otherBenefits: 'Concierge services, air accident cover',
    eligibility: 'Net monthly income ₹50,000+',
  },
  {
    name: 'IndusInd Bank Iconia',
    bank: 'IndusInd Bank',
    category: 'travel',
    annualFee: 10000,
    joiningFee: 10000,
    rewardPoints: 'Accelerated reward points on international and travel spends',
    welcomeBenefits: '10,000 bonus reward points',
    loungeAccess: 'Unlimited domestic and international lounge access',
    fuelBenefits: '2.5% surcharge waiver',
    offers: 'Complimentary memberships, golf games, spa services',
    otherBenefits: 'Comprehensive travel insurance, concierge services',
    eligibility: 'Net monthly income ₹1,50,000+',
  },

  // Standard Chartered Cards
  {
    name: 'Standard Chartered Ultimate',
    bank: 'Standard Chartered',
    category: 'cashback',
    annualFee: 5000,
    joiningFee: 5000,
    rewardPoints: '3.3% cashback on travel, dining, international spends. 1.5% on others',
    welcomeBenefits: 'Welcome benefit vouchers',
    loungeAccess: '6 domestic and 2 international lounge visits per quarter',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'Premium lifestyle benefits and dining privileges',
    otherBenefits: 'Travel insurance, concierge services',
    eligibility: 'Net monthly income ₹75,000+',
  },
  {
    name: 'Standard Chartered DigiSmart',
    bank: 'Standard Chartered',
    category: 'shopping',
    annualFee: 499,
    joiningFee: 499,
    rewardPoints: '5% cashback on online spends up to ₹500 per month',
    welcomeBenefits: 'Welcome vouchers on card activation',
    loungeAccess: 'Not available',
    fuelBenefits: 'No fuel benefits',
    offers: 'Special offers on e-commerce platforms',
    otherBenefits: 'Contactless payment, instant digital card',
    eligibility: 'Net monthly income ₹20,000+',
  },

  // American Express Cards
  {
    name: 'American Express Platinum Card',
    bank: 'American Express',
    category: 'travel',
    annualFee: 60000,
    joiningFee: 60000,
    rewardPoints: '5 membership reward points per ₹50 spent. 10x on hotel bookings',
    welcomeBenefits: 'Complimentary Taj InnerCircle membership, welcome bonus points',
    loungeAccess: 'Unlimited Priority Pass lounge access worldwide',
    fuelBenefits: 'Premium fuel benefits',
    offers: 'Fine Dining Program, hotel benefits, concierge services',
    otherBenefits: 'Comprehensive travel insurance, golf, wellness benefits',
    eligibility: 'Invitation only or very high income',
  },
  {
    name: 'American Express SmartEarn',
    bank: 'American Express',
    category: 'cashback',
    annualFee: 495,
    joiningFee: 495,
    rewardPoints: '5% cashback on telecom, Amazon, Flipkart. 1% on others',
    welcomeBenefits: '500 bonus reward points',
    loungeAccess: '2 domestic lounge visits per quarter',
    fuelBenefits: '1% fuel surcharge waiver',
    offers: 'E-commerce discounts and partner offers',
    otherBenefits: 'Zero lost card liability, purchase protection',
    eligibility: 'Net monthly income ₹25,000+',
  },
];

async function main() {
  console.log('Start seeding...');

  for (const card of creditCards) {
    const creditCard = await prisma.creditCard.create({
      data: card,
    });
    console.log(`Created card: ${creditCard.name}`);
  }

  console.log('Seeding finished.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
